version: 2

jobs:
  build:
    working_directory: ~/the-difference-engine/we-r-next-generation-web
    parallelism: 1
    shell: /bin/bash --login
    
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    
    # Look at changing this imagehttps://circleci.com/docs/2.0/circleci-images/
    docker:
      - image: circleci/build-image:ubuntu-14.04-XXL-upstart-1189-5614f37
        command: /sbin/init

    steps:
      - checkout
      - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
      # This is based on your 1.0 configuration file or project settings
      - run:
          working_directory: ~/the-difference-engine/we-r-next-generation-web
          command: nvm install 8.9.4 && nvm alias default 8.9.4

      # Restore the dependency cache
      - restore_cache:
          keys:
          # This branch if available
          - v1-dep-${CIRCLE_BRANCH}-
          # Default branch if not
          - v1-dep-master-
          # Any branch if there are none on the default branch - this should be unnecessary if you have your default branch configured correctly
          - v1-dep-

      - run: if [ -z "${NODE_ENV:-}" ]; then export NODE_ENV=test; fi
      - run: export PATH="~/the-difference-engine/we-r-next-generation-web/node_modules/.bin:$PATH"
      
      # Install project dependencies
      - run:
          name: Install local dependencies
          command: npm install

      # Save dependency cache
      - save_cache:
          key: v1-dep-${CIRCLE_BRANCH}-${CIRCLE_BUILD_NUM}
          paths:
              - node_modules

      # # Lint the source code
      # - run:
      #   name: Linting
      #   command: npm run lint

      # # Test the source code
      # - run:
      #   name: Testing
      #   command: npm run test

      # Build project
      - run:
          name: Building
          command: npm run build --config build/webpack.prod.conf.js

      # Cache the dist folder for the deploy job
      - save_cache:
          key: v1-dist-${CIRCLE_BRANCH}-${CIRCLE_BUILD_NUM}
          paths:
              - dist

  deploy:
    working_directory: ~/the-difference-engine/we-r-next-generation-web
    docker:
        - image: circleci/build-image:ubuntu-14.04-XXL-upstart-1189-5614f37
    steps:
        # Restore cache from the build job which contains the
        # dist folder that needs to be deployed
        - restore_cache:
            key: v1-dist-${CIRCLE_BRANCH}-${CIRCLE_BUILD_NUM}

        - run:
            name: Deploy to S3
            command: aws --region us-east-2 s3 cp dist s3://wrng --recursive

workflows:
  version: 2
  # The build and deploy workflow
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
